### PR TITLE
chore: make examples work

### PR DESCRIPTION
**Pull request by olizilla**
- Move examples to their own directory and give them all the packge.json they need to be runnable.
- Fix imports since some things got moved around in multiformats
- Update readme and fix imports in example

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by olizilla** [comment]
_signs of life_

```console
~/Code/ipld/js-car/examples on make-examples-work  
❯ ./round-trip.js                                                                12:27:58
Retrieved [random meaningless bytes] from example.car with CID [bafkreihwkf6mtnjobdqrkiksr7qhp6tiiqywux64aylunbvmfhzeql2coa]

~/Code/ipld/js-car/examples on make-examples-work  
❯ ./verify-car.js example.car                                                    12:28:02
.⏎                                                                                       
~/Code/ipld/js-car/examples on make-examples-work  
❯ ./dump-car.js example.car                                                      12:28:22
bafkreihwkf6mtnjobdqrkiksr7qhp6tiiqywux64aylunbvmfhzeql2coa [raw]
'{"0":114,"1":97,"10":110,"11":105,"12":110,"13":103,"14":108,"15":101,"16":115,"17":115,"18":32,"19":98,"2":110,"20":121,"21":116,"22":101,"23":115,"3":100,"4":111,"5":109,"6":32,"7":109,"8":101,"9":97}'
```

**Comment by olizilla** [comment]
Mildy related minor feedback... My assumption picking up this module was that it would verify each block for me. The examples make it clear that it's not how that works, but it might be worth stating clearly in the readme that this is just for iterating over blocks, and the user needs to bring their own validating.

**Comment by rvagg** [comment]
Thanks!

I've pushed a commit here that adds a bit in the README about verification, it also fixes the typechecking and building rules for the examples _and_ adds a little test for running the examples so they shouldn't be overlooked again (this isn't the first time they've been left broken).

There was also an error on the verify-car.js example that I've fixed (it re-used the original digest to build the CID it was comparing!) and I've extended that example a little to demonstrate the simplest path to verifying the CIDs because it's very unlikely people will be interested in a full round-trip test.

Regarding _why_ it doesn't verify for you - it comes down to multihash availability. There's no limit on the multihashes you may find in CIDs and we don't want to ship `@ipld/car` with all possible multihashes we have for JavaScript, so it's one of those things you have to push further out to the edges. The ideal world for IPLD is a better plugin system where these things bundle up into something like https://github.com/ipld/js-block that you can plug the functionality into (codecs and multihashes) and have it do all the things within those bounds. At the edges though, these components can't assume much about what's available.

**Comment by olizilla** [comment]
Absolutely. It makes sense, this is focused on the car file format. The car file import/export tools that we want to exist get to make the decisions about what codecs'n'hashes to include.

**Pull request merged**
