### PR TITLE
fix: updates for latest multiformats

### PR DESCRIPTION
**Pull request by rvagg**
this needs the newer types dist changes migrated from multiformats when finalised there

### CODE REVIEW

**Comment by rvagg** [comment]
this is against https://github.com/multiformats/js-multiformats/pull/70, so won't pass until that's published

**Comment by Gozala** [comment]
Here is the module resolution trace from TS which seems to suggest `multiformats/cid` is resolved as expected:

```
======== Resolving module 'multiformats/cid' from '/Users/gozala/Projects/js-car/lib/coding.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'baseUrl' option is set to '/Users/gozala/Projects/js-car', using this value to resolve non-relative module name 'multiformats/cid'.
'paths' option is specified, looking for a pattern to match module name 'multiformats/cid'.
'baseUrl' option is set to '/Users/gozala/Projects/js-car', using this value to resolve non-relative module name 'multiformats/cid'.
Resolving module name 'multiformats/cid' relative to base url '/Users/gozala/Projects/js-car' - '/Users/gozala/Projects/js-car/multiformats/cid'.
Loading module as file / folder, candidate module location '/Users/gozala/Projects/js-car/multiformats/cid', target file type 'TypeScript'.
Loading module 'multiformats/cid' from 'node_modules' folder, target file type 'TypeScript'.
Directory '/Users/gozala/Projects/js-car/lib/node_modules' does not exist, skipping all lookups in it.
Found 'package.json' at '/Users/gozala/Projects/js-car/node_modules/multiformats/package.json'.
'package.json' has a 'typesVersions' field with version-specific path mappings.
'package.json' has a 'typesVersions' entry '*' that matches compiler version '4.2.3', looking for a pattern to match module name 'cid'.
Module name 'cid', matched pattern '*'.
Trying substitution 'types/*', candidate module location: 'types/cid'.
File '/Users/gozala/Projects/js-car/node_modules/multiformats/types/cid.ts' does not exist.
File '/Users/gozala/Projects/js-car/node_modules/multiformats/types/cid.tsx' does not exist.
File '/Users/gozala/Projects/js-car/node_modules/multiformats/types/cid.d.ts' exist - use it as a name resolution result.
Resolving real path for '/Users/gozala/Projects/js-car/node_modules/multiformats/types/cid.d.ts', result '/Users/gozala/Projects/js-car/node_modules/multiformats/types/cid.d.ts'.
======== Module name 'multiformats/cid' was successfully resolved to '/Users/gozala/Projects/js-car/node_modules/multiformats/types/cid.d.ts' with Package ID 'multiformats/types/cid.d.ts@4.6.3'. ========
```

But problem is that there is no `export CID` in that file instead there is `export default CID` which is what causes errors

**Comment by Gozala** [comment]
I have tried my best to get this resolved but it seems there is a combination of bugs that either breaks js-car or breaks ts-use example in js-multiformats. If we do use `*` in `typeVersions` and `types` field that runs into microsoft/TypeScript#41284

If we do not use `types` field all the modules resolve except for `multiformats`.

If we do use `multiformats/*` pattern in multiformats it works here, but it breaks usage from project that is written in TS as our test in the multiformats repo

At this point I'm not sure if there is a reasonable way to get any of this to work

**Comment by Gozala** [comment]
Found a workaround and submitted https://github.com/multiformats/js-multiformats/pull/72

**Comment by rvagg** [comment]
Pulled in the enhancement from #8 to here, also copied an additional enhancement from multiformats/js-multiformats#70 that fixes the `*.ts.map` files by copying in source (and tests in this case) into the dist and running `tsc` in there. The maps come out nicely, the published asset includes all the things (my preference!) including examples, original source (with comments and types) and tests.

Will update when multiformats/js-multiformats#70 is done and copy the same enhancements to the codecs.

**Comment by rvagg** [comment]
This is passing now with multiformats@6.0.0 as per multiformats/js-multiformats#70

I'm pretty happy with the pattern emerging here, it seems to be ticking the boxes we care about as far as I can tell.

**Comment by rvagg** [comment]
updated to today's multiformats and codecs, removed a bunch of ts-ignores, expanded typing checking and improved the published version a little 🤞

**Pull request merged**
